"""Generate tessellated room surfaces for visible spotlight illumination.

MuJoCo's native renderer evaluates the legacy OpenGL lighting model at mesh
vertices. A single four-vertex wall therefore cannot show a small spotlight:
if the cone misses all four corners, the entire quad remains dark. These
64-by-64 grids provide enough vertices for the light cone to appear while the
checkerboard textures remain continuous.
"""

from __future__ import annotations

from pathlib import Path


ASSET_DIR = Path(__file__).resolve().parent / "assets"
SUBDIVISIONS = 64

SURFACES = {
    "left_wall_surface.obj": (
        (0.0, -0.32, -0.45),
        (0.0, 0.64, 0.0),
        (0.0, 0.0, 0.90),
    ),
    "right_wall_surface.obj": (
        (0.0, 0.32, -0.45),
        (0.0, -0.64, 0.0),
        (0.0, 0.0, 0.90),
    ),
    "back_wall_surface.obj": (
        (-0.39, 0.0, -0.45),
        (0.78, 0.0, 0.0),
        (0.0, 0.0, 0.90),
    ),
    "ceiling_surface.obj": (
        (-0.39, -0.32, 0.0),
        (0.0, 0.64, 0.0),
        (0.78, 0.0, 0.0),
    ),
}


def _point(origin, u_axis, v_axis, u, v):
    return tuple(
        origin[index] + (u_axis[index] * u) + (v_axis[index] * v)
        for index in range(3)
    )


def _surface_obj(origin, u_axis, v_axis) -> str:
    lines = [
        "# Generated by sim/generate_room_meshes.py",
        f"# {SUBDIVISIONS} x {SUBDIVISIONS} lighting grid",
    ]
    row_width = SUBDIVISIONS + 1

    for v_index in range(row_width):
        v = v_index / SUBDIVISIONS
        for u_index in range(row_width):
            u = u_index / SUBDIVISIONS
            x, y, z = _point(origin, u_axis, v_axis, u, v)
            lines.append(f"v {x:.8f} {y:.8f} {z:.8f}")

    for v_index in range(row_width):
        v = v_index / SUBDIVISIONS
        for u_index in range(row_width):
            u = u_index / SUBDIVISIONS
            lines.append(f"vt {u:.8f} {v:.8f}")

    for v_index in range(SUBDIVISIONS):
        for u_index in range(SUBDIVISIONS):
            lower_left = (v_index * row_width) + u_index + 1
            lower_right = lower_left + 1
            upper_left = lower_left + row_width
            upper_right = upper_left + 1
            lines.append(
                f"f {lower_left}/{lower_left} "
                f"{lower_right}/{lower_right} "
                f"{upper_right}/{upper_right}"
            )
            lines.append(
                f"f {lower_left}/{lower_left} "
                f"{upper_right}/{upper_right} "
                f"{upper_left}/{upper_left}"
            )

    return "\n".join(lines) + "\n"


def ensure_room_meshes() -> None:
    """Create or refresh the deterministic room-surface OBJ assets."""

    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    for filename, axes in SURFACES.items():
        path = ASSET_DIR / filename
        content = _surface_obj(*axes)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    ensure_room_meshes()
    print(
        f"Generated {len(SURFACES)} room meshes at "
        f"{SUBDIVISIONS} x {SUBDIVISIONS} subdivisions"
    )
